# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-10 16:19
from __future__ import unicode_literals

import wizard_builder.models

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('wizard_builder', '0002_remove_formquestion_example'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='questionpage',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='textpage',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='pagebase',
            name='site',
            field=models.ForeignKey(default=wizard_builder.models.get_current_site_wrapper, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
