# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-02 22:49
from __future__ import unicode_literals

from django.db import migrations, models


def copy_pagebase_id(apps, schema_editor):
    current_database = schema_editor.connection.alias
    Page = apps.get_model('wizard_builder.Page')
    for page in Page.objects.using(current_database):
        Page.objects.filter(
            pk=page.pk,
        ).update(
            new_id=page.pagebase_ptr_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('wizard_builder', '0012_questionpage_to_page'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='page',
        #     name='new_id',
        #     field=models.AutoField(auto_created=True, null=True, serialize=False),
        # ),
        # migrations.RunPython(
        #     copy_pagebase_id,
        #     reverse_code=migrations.RunPython.noop,
        # ),
        # migrations.AlterField(
        #     model_name='page',
        #     name='new_id',
        #     field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        # ),
    ]
