# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 00:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard_builder', '0013_admin_html_and_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkbox',
            options={'verbose_name_plural': 'checkboxes'},
        ),
    ]
