# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard_builder', '0014_checkboxes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.DeleteModel(
            name='SingleLineTextWithMap',
        ),
    ]
