# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard_builder', '0015_remove_unused_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultiLineText',
        ),
    ]
