# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard_builder', '0034_move_choice_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkbox',
            name='multiplechoice_ptr',
        ),
        migrations.RemoveField(
            model_name='multiplechoice',
            name='formquestion_ptr',
        ),
        migrations.RemoveField(
            model_name='radiobutton',
            name='multiplechoice_ptr',
        ),
        migrations.RemoveField(
            model_name='singlelinetext',
            name='formquestion_ptr',
        ),
        migrations.RemoveField(
            model_name='textarea',
            name='formquestion_ptr',
        ),
        migrations.DeleteModel(
            name='Checkbox',
        ),
        migrations.DeleteModel(
            name='MultipleChoice',
        ),
        migrations.DeleteModel(
            name='RadioButton',
        ),
        migrations.DeleteModel(
            name='SingleLineText',
        ),
        migrations.DeleteModel(
            name='TextArea',
        ),
    ]
