# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard_builder', '0037_auto_20171028_0142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleChoice',
        ),
    ]
