engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - python
  radon:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.py"
exclude_paths:
- callisto_core/tests/
- */migrations/*
