# Generated by Django 2.0.1 on 2018-01-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='site_id',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
