# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_invalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='site_id',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
