# Generated by Django 2.0.9 on 2019-06-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0002_auto_20180103_1628")]

    operations = [
        migrations.AddField(
            model_name="account",
            name="email_index",
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name="account",
            name="encrypted_email",
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name="account",
            name="encrypted_username",
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name="account",
            name="username_index",
            field=models.CharField(default=False, max_length=255),
        ),
    ]
