# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkAccount',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('emails',
                 models.TextField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
