# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-10 16:19
from __future__ import unicode_literals

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models

import wizard_builder.models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
        ('callisto_core.wizard_builder', '0002_remove_formquestion_example'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='questionpage',
            managers=[
                ('objects',
                 django.db.models.manager.Manager()),
                ('base_objects',
                 django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='textpage',
            managers=[
                ('objects',
                 django.db.models.manager.Manager()),
                ('base_objects',
                 django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='pagebase',
            name='site',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='sites.Site',
                null=True),
        ),
    ]
