# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("wizard_builder", "0006_many_sites")]

    operations = [
        migrations.RemoveField(model_name="conditional", name="page"),
        migrations.RemoveField(model_name="conditional", name="question"),
        migrations.DeleteModel(name="Conditional"),
    ]
