# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callisto_core.wizard_builder', '0007_remove_conditional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textpage',
            name='pagebase_ptr',
        ),
        migrations.AlterModelOptions(
            name='pagebase',
            options={},
        ),
        migrations.DeleteModel(
            name='TextPage',
        ),
    ]
