# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callisto_core.wizard_builder', '0009_pagebase_to_questionpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagebase',
            name='position',
        ),
        migrations.RemoveField(
            model_name='pagebase',
            name='section',
        ),
        migrations.RemoveField(
            model_name='pagebase',
            name='sites',
        ),
    ]
