# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("wizard_builder", "0010_remove_pagebase_attrs")]

    operations = [
        migrations.RenameField(
            model_name="questionpage", old_name="new_position", new_name="position"
        ),
        migrations.RenameField(
            model_name="questionpage", old_name="new_section", new_name="section"
        ),
        migrations.RenameField(
            model_name="questionpage", old_name="new_sites", new_name="sites"
        ),
    ]
