# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 21:21
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models

# import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard_builder', '0014_questionpage_to_page_3'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='formquestion',
        #     name='descriptive_text',
        #     field=tinymce.models.HTMLField(blank=True),
        # ),
        # migrations.AlterField(
        #     model_name='formquestion',
        #     name='text',
        #     field=tinymce.models.HTMLField(),
        # ),
        # migrations.AlterField(
        #     model_name='page',
        #     name='infobox',
        #     field=tinymce.models.HTMLField(blank=True),
        # ),
    ]
