# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard_builder', '0021_choiceoption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choiceoption',
            old_name='question',
            new_name='choice',
        ),
    ]
