# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 22:46
from __future__ import unicode_literals

from django.db import migrations

# import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard_builder', '0022_choiceoption_typo'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='formquestion',
        #     name='text',
        #     field=tinymce.models.HTMLField(blank=True),
        # ),
    ]
