# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("wizard_builder", "0024_remove_formquestion_added")]

    operations = [
        migrations.AlterField(
            model_name="formquestion",
            name="descriptive_text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="formquestion", name="text", field=models.TextField(blank=True)
        ),
        migrations.AlterField(
            model_name="page", name="infobox", field=models.TextField(blank=True)
        ),
    ]
