# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("wizard_builder", "0025_auto_20170915_0948")]

    operations = [migrations.RemoveField(model_name="page", name="infobox")]
