# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("wizard_builder", "0032_move_question_dropdown")]

    operations = [
        migrations.AddField(
            model_name="checkbox", name="temp_04", field=models.TextField(null=True)
        ),
        migrations.AddField(
            model_name="multiplechoice",
            name="temp_03",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="radiobutton", name="temp_05", field=models.TextField(null=True)
        ),
        migrations.AddField(
            model_name="singlelinetext",
            name="temp_01",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="textarea", name="temp_02", field=models.TextField(null=True)
        ),
    ]
