# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 23:56
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


def move_choice_question(apps, schema_editor):
    current_database = schema_editor.connection.alias
    Choice = apps.get_model('callisto_core.wizard_builder.Choice')
    for choice in Choice.objects.using(current_database):
        base_question = choice.question.formquestion_ptr
        choice.new_question = base_question
        choice.save()


class Migration(migrations.Migration):

    dependencies = [
        ('callisto_core.wizard_builder', '0034c_move_choice_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
    ]
