# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 01:42
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard_builder',
         '0036_checkbox_multiplechoice_radiobutton_singlelinetext_textarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='wizard_builder.FormQuestion'),
        ),
    ]
