# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("wizard_builder", "0040_populate_dropdown")]

    operations = [migrations.RemoveField(model_name="formquestion", name="is_dropdown")]
