# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callisto_core.wizard_builder', '0043_multiplechoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formquestion',
            name='descriptive_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
