# Generated by Django 2.0.1 on 2018-01-10 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard_builder', '0049_copy_sites_from_page_to_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='sites',
        ),
    ]
