# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_add_encryption_fields_to_match_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchreport',
            name='identifier',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
