# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_make_salt_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentreport',
            name='to_address',
            field=models.CharField(max_length=4096),
        ),
    ]
