# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_auto_20170814_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchreport',
            name='contact_email',
        ),
    ]
