# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_remove_matchreport_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='contact_notes',
            field=models.TextField(default='No Preference'),
        ),
    ]
