# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_report_contact_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchreport',
            name='identifier',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
