# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("delivery", "0017_remove_report_autosaved")]

    operations = [migrations.RemoveField(model_name="matchreport", name="identifier")]
