# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0017_remove_report_autosaved'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='Record',
        ),
    ]
