# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0019_report_record_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentmatchreport',
            old_name='reports',
            new_name='records',
        ),
    ]
