# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("delivery", "0019_auto_20171119_1543")]

    operations = [migrations.RemoveField(model_name="matchreport", name="seen")]
