# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("delivery", "0021a_copy_attrs")]

    operations = [
        migrations.RemoveField(model_name="sentreport", name="sent"),
        migrations.RemoveField(model_name="sentreport", name="to_address"),
    ]
