# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("delivery", "0022_auto_20171122_1434")]

    operations = [
        migrations.RenameField(
            model_name="sentfullreport", old_name="new_sent", new_name="sent"
        ),
        migrations.RenameField(
            model_name="sentfullreport",
            old_name="new_to_address",
            new_name="to_address",
        ),
        migrations.RenameField(
            model_name="sentmatchreport", old_name="new_sent", new_name="sent"
        ),
        migrations.RenameField(
            model_name="sentmatchreport",
            old_name="new_to_address",
            new_name="to_address",
        ),
    ]
