# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 14:37
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("delivery", "0023_auto_20171122_1435")]

    operations = [
        migrations.CreateModel(
            name="NewSentFullReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent", models.DateTimeField(auto_now_add=True)),
                ("to_address", models.TextField(null=True)),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="delivery.Report",
                    ),
                ),
            ],
        )
    ]
