# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 14:24
from __future__ import unicode_literals

import uuid

from django.db import migrations


def copy_attrs(apps, schema_editor):
    current_database = schema_editor.connection.alias
    Report = apps.get_model('delivery.Report')
    for row in Report.objects.using(current_database):
        row.uuid = uuid.uuid4()
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0036_auto_20171122_1454'),
    ]

    operations = [
        migrations.RunPython(
            copy_attrs,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
