# Generated by Django 2.0 on 2017-12-08 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("delivery", "0038_uuid_unique_constraint")]

    operations = [
        migrations.AlterField(
            model_name="matchreport",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="delivery.Report"
            ),
        )
    ]
