# Generated by Django 2.0.4 on 2018-06-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0040_auto_20171215_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerpIDTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
            ],
        ),
    ]
