# Generated by Django 2.2.2 on 2019-07-02 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("delivery", "0040_auto_20171215_0302")]

    operations = [
        migrations.RemoveField(model_name="report", name="contact_email"),
        migrations.RemoveField(model_name="report", name="contact_name"),
        migrations.RemoveField(model_name="report", name="contact_notes"),
        migrations.RemoveField(model_name="report", name="contact_phone"),
        migrations.RemoveField(model_name="report", name="contact_voicemail"),
        migrations.DeleteModel(name="RecordHistorical"),
    ]
