# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-30 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_email_notification_data_migration')
    ]

    state_operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=77)),
                ('body', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        )
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
    ]
