# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-07 15:23
from __future__ import unicode_literals

from django.db import migrations, models

import callisto.notification.models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('notification', '0001_initial_create_email_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='sites',
            field=models.ManyToManyField(default=callisto.notification.models.get_current_site_wrapper, to='sites.Site'),
        ),
    ]
