# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-29 16:18
from __future__ import unicode_literals

from django.db import migrations


def populate_email_notification_forwards(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    NewEmailNotification = apps.get_model('notification', 'NewEmailNotification')
    EmailNotification = apps.get_model('delivery', 'EmailNotification')

    for email_notification in EmailNotification.objects.using(db_alias).all():
        NewEmailNotification.objects.using(db_alias).create(
            name=email_notification.name,
            subject=email_notification.subject,
            body=email_notification.body,
        )

def populate_email_notification_backwards(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    NewEmailNotification = apps.get_model('notification', 'NewEmailNotification')
    NewEmailNotification.objects.using(db_alias).all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            populate_email_notification_forwards,
            populate_email_notification_backwards,
        ),
    ]
