# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("notification", "0003_tempemailnotification")]

    operations = [
        migrations.RemoveField(model_name="emailnotification", name="sites"),
        migrations.DeleteModel(name="EmailNotification"),
    ]
