# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_delete_old_email_notification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TempEmailNotification',
            new_name='EmailNotification',
        ),
    ]
