# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchreport',
            name='encrypted',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='salt',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
