# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_report_autosaved'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchreport',
            name='encode_prefix',
            field=models.CharField(max_length=500, blank=False),
        ),
        migrations.AddField(
            model_name='report',
            name='encode_prefix',
            field=models.CharField(max_length=500, blank=False),
        ),
        migrations.AlterField(
            model_name='matchreport',
            name='salt',
            field=models.CharField(max_length=256, blank=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='salt',
            field=models.CharField(max_length=256, blank=False),
        ),
    ]
