# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-30 16:15
from __future__ import unicode_literals

from django.db import migrations


def update_content_types_forward(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    content_type = ContentType.objects.filter(
        app_label='delivery',
        model='emailnotification',
    ).first()
    if content_type:
        content_type.app_label = 'notification'
        content_type.save()

def update_content_types_reverse(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    content_type = ContentType.objects.filter(
        app_label='notification',
        model='emailnotification',
    ).first()
    if content_type:
        content_type.app_label = 'delivery'
        content_type.save()

class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_to_address_to_textfield'),
    ]

    database_operations = [
        migrations.AlterModelTable('EmailNotification', 'notification_emailnotification')
    ]

    state_operations = [
        migrations.DeleteModel('EmailNotification')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations,
        ),
        migrations.RunPython(
            update_content_types_forward,
            update_content_types_reverse,
        ),
    ]
