# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-30 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_to_address_to_textfield'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailNotification',
            new_name='LegacyEmailNotification',
        ),
    ]
