# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-30 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_rename_email_notification'),
    ]

    database_operations = [
        migrations.AlterModelTable('LegacyEmailNotification', 'notification_emailnotification')
    ]

    state_operations = [
        migrations.DeleteModel('LegacyEmailNotification')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations,
        ),
    ]
