# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-30 16:15
from __future__ import unicode_literals

from django.db import migrations


# source: http://stackoverflow.com/a/26472482/3055558
class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_rename_email_notification'),
    ]

    database_operations = [
        migrations.AlterModelTable('LegacyEmailNotification', 'notification_emailnotification')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
        ),
        migrations.AlterModelOptions(
            name='legacyemailnotification',
            options={'managed': False},
        ),
    ]
