from django.conf.urls import include, url
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.views.generic.base import RedirectView

from ..delivery import views, wizard

urlpatterns = [
    url(r'^$',
        RedirectView.as_view(url=reverse_lazy('report_new')),
        name='index',
        ),
    url(r'^report/new/$',
        views.ReportCreateView.as_view(),
        name='report_new',
        ),
    url(r'^report/uuid/(?P<uuid>.+)/$',
        views.ReportAccessView.as_view(),
        name='report_update',
        ),
    url(r'^report/uuid/(?P<uuid>.+)/wizard/new/$',
        wizard.RedirectWizardView.as_view(),
        name='wizard_new',
        ),
    url(r'^report/uuid/(?P<uuid>.+)/wizard/step/(?P<step>.+)/$',
        wizard.EncryptedWizardView.as_view(),
        name='wizard_update',
        ),
    url(r'^submission/submit/(?P<report_id>\d+)/$', views.submit_report_to_authority, name="test_submit_report"),
    url(r'^submission/submit_custom/(?P<report_id>\d+)/$', views.submit_report_to_authority,
        {'form_template_name': 'submit_report_to_authority_custom.html',
         'confirmation_template_name': 'submit_report_to_authority_confirmation_custom.html',
         'extra_context': {'test': 'custom context'}}, name="test_submit_confirmation"),
    url(r'^submission/match/(?P<report_id>\d+)/$', views.submit_to_matching, name="test_submit_match"),
    url(r'^submission/match_custom/(?P<report_id>\d+)/$', views.submit_to_matching,
        {'form_template_name': 'submit_to_matching_custom.html',
         'confirmation_template_name': 'submit_to_matching_confirmation_custom.html',
         'extra_context': {'test': 'custom context'}}, name="test_match_confirmation"),
    url(r'^submission/withdraw_match/(?P<report_id>\d+)/$', views.withdraw_from_matching,
        {'template_name': 'after_withdraw.html',
         'extra_context': {'test': 'custom context'}}, name="test_withdraw_match"),
    url(r'^submission/export/(?P<report_id>\d+)/$', views.export_as_pdf, name="test_export"),
    url(r'^submission/export_custom/(?P<report_id>\d+)/$', views.export_as_pdf,
        {'extra_context': {'test': 'custom context'}}, name="test_export_custom"),
    url(r'^submission/delete/(?P<report_id>\d+)/$', views.delete_report,
        {'extra_context': {'test': 'custom context'}}, name="delete_report"),
    url(r'^nested_admin/', include('nested_admin.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^admin/', admin.site.urls),
]
